---
title: "Gapminder Exercise Template"
author: "Michele Caprio"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 7)
```


## Load packages

```{r message=FALSE}
library(tidyverse)
```

```{r}
x <- 2
x*3
```

## Load data

```{r message=FALSE}
gap <- read_csv("https://bit.ly/gap_data_upd")
```

more text..

## Exercises

### Exercise 1

How many observations are in this dataset?

```{r number_rows_gap}
num_rows <- nrow(gap)
```

There are `r num_rows` obs in the dataset


### Exercise 2

Visualize the relationship between GDP and life expectancy for 
countries in Europe in 1952 using a scatter plot.

```{r eu_52}
eu_52<-gap%>%
  filter(continent=="Europe", year==1952)
ggplot(data=eu_52, aes(x=gdpPercap, y=lifeExp))+
  geom_point()
```

### Exercise 3

Add year 1967 in another color.

```{r eu_52_67}
eu_52_67<-gap%>%
  filter(continent=="Europe", year %in% c(1952, 1967))
ggplot(data=eu_52_67, aes(x=gdpPercap, y=lifeExp, color=factor(year)))+
  geom_point()
```

